apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
  namespace: production
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: google/cloud-sdk:alpine
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e && \
                  apk add --no-cache postgresql-client && \
                  
                  pg_dump -h $PGHOST -U $PGUSER -d $PGDATABASE > /tmp/backup.sql && \
                  
                  gcloud auth activate-service-account --key-file=/var/secrets/google/key.json && \
                  
                  gsutil cp /tmp/backup.sql gs://eerojantunen-project-backup-bucket/backup-$(date +%Y-%m-%d).sql
              
              env:
                - name: PGHOST
                  value: "project-postgres-svc"
                - name: PGDATABASE
                  value: "postgres"
                - name: PGUSER
                  value: "postgres"
                - name: PGPASSWORD
                  value: "pass123"

              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
                  readOnly: true

          volumes:
            - name: google-cloud-key
              secret:
                secretName: google-service-account

          restartPolicy: OnFailure